name: neatclean

version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1G

  web:
    image: ${DOCKER_REGISTRY:-ghcr.io}/${GITHUB_REPOSITORY:-shadowjumper3000/neatclean}:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    restart: always
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=3306
      - DJANGO_ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - STATIC_ROOT=/app/staticfiles
      - STATIC_URL=/static/
      - MEDIA_ROOT=/app/media
      - MEDIA_URL=/media/
    volumes:
      - static_files:/app/staticfiles:rw
      - media_files:/app/media:rw
    networks:
      - network
    depends_on:
      db:
        condition: service_healthy
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health/" ]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "8000:8000"

networks:
  network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  media_files:
    driver: local
  static_files:
    driver: local
