FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    default-libmysqlclient-dev \
    build-essential \
    pkg-config \
    netcat-traditional \
    python3-dev \
    libjpeg-dev \
    zlib1g-dev \
    libpng-dev \
    && rm -rf /var/lib/apt/lists/*

# Create media directory and set permissions
RUN mkdir -p /app/media/profile_pictures && \
    chmod -R 755 /app/media

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt