name: neatclean_dev

version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=neatclean
      - MYSQL_USER=django_user
      - MYSQL_PASSWORD=devpassword
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - mysql_data_dev:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    image: neatclean:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=devsecretkey
      - DB_NAME=neatclean
      - DB_USER=django_user
      - DB_PASSWORD=devpassword
      - DB_HOST=db
      - DB_PORT=3306
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "
        echo 'Waiting for database...' &&
        while ! nc -z db 3306; do
          sleep 1
        done &&
        echo 'Database is ready!' &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "

volumes:
  mysql_data_dev:
    name: neatclean_mysql_data_dev
