# Generated by Django 5.1.5 on 2025-02-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_customer_password_staff_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
